### ISSUE TITLE
License cleanup

### ISSUE THREAD

**Issue by andyli** [Chris00/ocaml-rope#1]
When packaging rope for Debian, we noticed that there is some license inconsistency.

 * The LICENSE file is LGPL-2.1+ (with linking exception).
 * The header of bench/tinyRope.* is GNU **Library** General Public License 2.0+ (with linking exception).

According to https://www.gnu.org/licenses/old-licenses/lgpl-2.0.en.html, it is recommended to replace GNU **Library** General Public License with GNU **Lesser** General Public License.

The FSF address in the files (both the headers and the LICENSE file) also need updating: https://lintian.debian.org/tags/old-fsf-address-in-copyright-file.html

Finally, the copyright owner info is inconsistent.

 * The LICENSE file stated only Christophe Troestler
 * bench/bm_ropes.ml: Christophe Troestler and Mauricio Fernandez
 * bench/tinyRope.*: Mauricio Fernandez

While copyright of individual files can be of different owners, I guess it is better to mention Mauricio Fernandez in the top-level LICENSE file. It's just my suggestion though.

**Comment by Chris00** [comment]
Files in `bench/` are not really part of the library — they are just benchmarks, comparing it to other possibilities.  `bench/bm_ropes.ml` has not been modified by Mauricio Fernandez, I put his name because it depends on his library.  Would mentioning this in the README be enough?

**Comment by andyli** [comment]
Umm... did you mean you copied some of his code in the file?

Mentioning that in the LICENSE file in 1-2 sentence would be more appropriate.

**Comment by Chris00** [comment]
Hopefully the above fix will suit you (tell me if not).

**Comment by Chris00** [comment]
You may want to wait that I port the build to jbuilder before packaging to Debian.  See https://github.com/Chris00/ocaml-rope/issues/2

**Comment by andyli** [comment]
That's better, thanks! There are 2 remaining issues:

 * incorrect FSF address
 * replacing the license of bench/tinyRope.* with GNU Lesser General Public License

> wait that I port the build to jbuilder before packaging to Debian

I think I will keep working on the current version for now and package the new one when you release it.
The jbuilder Debian package is quite new and has some issue: https://lists.debian.org/debian-ocaml-maint/2017/11/msg00057.html

**Comment by Chris00** [comment]
Was the issue reported upstream?

**Comment by Chris00** [comment]
Normally all is fixed.

**Comment by andyli** [comment]
The headers of bench/tinyRope.ml and bench/tinyRope.mli are not fully fixed. You may do a string replace of `Library General` with `Lesser General`.

**Comment by Chris00** [comment]
Done.
